### ISSUE TITLE
Testing harness - compare against another Wasm implementation

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/polkadot-verification#10]
It would be nice to have some assurance that we have the same behavior as other Wasm compilers/interpreters when executing the runtime.

If the tests are at the Rust level, they may also gives us some ideas about what sorts of properties are interesting for asking of KWasm.

Can we set up a testing harness which both KSubstrate and Substrate can run over the `node-template`?

Does `node-template` have a test-set?

**Comment by DemiMarie-parity** [comment]
Could we execute the parts of the Rust test suite that can be compiled to Wasm?

**Comment by DemiMarie-parity** [comment]
Also, there may be a general Wasm conformance test suite.  I can look for one.

**Comment by DemiMarie-parity** [comment]
There is an official Wasm test suite at [the WebAssembly Specification Repository](/WebAssembly/spec).
