### ISSUE TITLE
Make haskell backend able to take sequence of rules a argument

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/polkadot-verification#21]
It should receive a sequence of semantic rule identifiers (either by hash-id or numbers inserted by the frontend or location information), and apply those rules to a fully symbolic configuration in order.

This will produce a symbolic summary of the behavior along that execution path, without worrying about producing/discharging remainders.

**Comment by virgil-serbanuta** [comment]
Part 1: https://github.com/kframework/kore/pull/961

**Comment by virgil-serbanuta** [comment]
Part 2: https://github.com/kframework/kore/pull/983
(not submitted yet, not using the right rule identifiers, will probably need some tuning afterwards, e.g. if the original program executed `x=1; y=x` we don't know that the rules for the second instruction work with the same `x`).

**Comment by virgil-serbanuta** [comment]
Merged the above

**Comment by virgil-serbanuta** [comment]
Part 3, using the right identifiers:
https://github.com/kframework/kore/pull/1016

**Comment by ehildenb** [comment]
This is completed in the above three parts, so we just need to fix bugs (which will have their own cards).
