### ISSUE TITLE
Setup KWasm proofs on Haskell backend

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/polkadot-verification#8]
- [ ] Support for overloaded `<_>_`
- [ ] Passing proofs in tests/proofs on KWasm with haskell backend.

**Comment by traiansf** [comment]
@ehildenb currently there are at least two types of oveloads in the wasm-semantics.

1. the above mentioned `<_>_`
2. list overloads (e.g., `Stmts ::= Instrs | Decls`)

(2) seems significantly harder to tackle.  would it be possible to refactor the semantics to eliminate (subsorted) user defined lists?

**Comment by ehildenb** [comment]
Remember to add `-m KWASM-LEMMAS` (-m == --def-module)
